### ISSUE TITLE
bug: read overflow

### ISSUE THREAD

**Issue by MrCroxx** [foyer-rs/foyer#675]
```
2024-08-29 23:18:13.766	
  99:                0x0 - <unknown>
2024-08-29 23:18:13.766	
                               at ./misc/../sysdeps/unix/sysv/linux/aarch64/clone3.S:76
2024-08-29 23:18:13.766	
  98:     0xffff8099ba4c - thread_start
2024-08-29 23:18:13.766	
                               at ./nptl/pthread_create.c:447:8
2024-08-29 23:18:13.766	
  97:     0xffff8093597c - start_thread
2024-08-29 23:18:13.766	
                               at /rustc/72fdf913c53dd0e75313ba83e4aa80df3f6e2871/library/std/src/sys/pal/unix/thread.rs:108:17
2024-08-29 23:18:13.766	
  96:     0xaaaae8270b1c - std::sys::pal::unix::thread::Thread::new::thread_start::h798df216806ee4c6
2024-08-29 23:18:13.766	
                               at /rustc/72fdf913c53dd0e75313ba83e4aa80df3f6e2871/library/alloc/src/boxed.rs:2063:9
2024-08-29 23:18:13.766	
  95:     0xaaaae8270b1c - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h06c03745489277ae
2024-08-29 23:18:13.766	
                               at /rustc/72fdf913c53dd0e75313ba83e4aa80df3f6e2871/library/alloc/src/boxed.rs:2063:9
2024-08-29 23:18:13.766	
  94:     0xaaaae8270b1c - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hefea6fa2928853f2
2024-08-29 23:18:13.766	
                               at /rustc/72fdf913c53dd0e75313ba83e4aa80df3f6e2871/library/core/src/ops/function.rs:250:5
2024-08-29 23:18:13.766	
  93:     0xaaaae82ffc60 - core::ops::function::FnOnce::call_once{{vtable.shim}}::hcb3d85cc99c0b624
2024-08-29 23:18:13.766	
                               at /rustc/72fdf913c53dd0e75313ba83e4aa80df3f6e2871/library/std/src/thread/mod.rs:541:30
2024-08-29 23:18:13.766	
  92:     0xaaaae82ffc60 - std::thread::Builder::spawn_unchecked_::{{closure}}::h95ccbbd444a9554b
2024-08-29 23:18:13.766	
                               at /rustc/72fdf913c53dd0e75313ba83e4aa80df3f6e2871/library/std/src/panic.rs:149:14
2024-08-29 23:18:13.766	
  91:     0xaaaae82ffc60 - std::panic::catch_unwind::h33f36538c0fe2cad
2024-08-29 23:18:13.766	
                               at /rustc/72fdf913c53dd0e75313ba83e4aa80df3f6e2871/library/std/src/panicking.rs:523:19
2024-08-29 23:18:13.766	
  90:     0xaaaae82ffc60 - std::panicking::try::h6941fab7160eb50a
2024-08-29 23:18:13.766	
                               at /rustc/72fdf913c53dd0e75313ba83e4aa80df3f6e2871/library/std/src/panicking.rs:559:40
2024-08-29 23:18:13.766	
  89:     0xaaaae82ffc60 - std::panicking::try::do_call::h9387a64eb51ba08b
2024-08-29 23:18:13.766	
                               at /rustc/72fdf913c53dd0e75313ba83e4aa80df3f6e2871/library/core/src/panic/unwind_safe.rs:272:9
2024-08-29 23:18:13.766	
  88:     0xaaaae82ffc60 - <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::ha4eeb076740ce661
2024-08-29 23:18:13.766	
                               at /rustc/72fdf913c53dd0e75313ba83e4aa80df3f6e2871/library/std/src/thread/mod.rs:542:17
2024-08-29 23:18:13.766	
  87:     0xaaaae82ffc60 - std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}::h5071b143bf8500a3
2024-08-29 23:18:13.766	
                               at /rustc/72fdf913c53dd0e75313ba83e4aa80df3f6e2871/library/std/src/sys_common/backtrace.rs:155:18
2024-08-29 23:18:13.766	
  86:     0xaaaae8311d24 - std::sys_common::backtrace::__rust_begin_short_backtrace::he90ae8a8fdbb6ac2
2024-08-29 23:18:13.766	
                               at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.0/src/runtime/blocking/pool.rs:471:13
2024-08-29 23:18:13.766	
  85:     0xaaaae8311d24 - tokio::runtime::blocking::pool::Spawner::spawn_thread::{{closure}}::h1062652044a82452
2024-08-29 23:18:13.765	
                               at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.0/src/runtime/blocking/pool.rs:513:17
2024-08-29 23:18:13.765	
  84:     0xaaaae82f3be0 - tokio::runtime::blocking::pool::Inner::run::h8b9a64dc4bb36ea6
2024-08-29 23:18:13.765	
                               at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.0/src/runtime/blocking/pool.rs:159:9
2024-08-29 23:18:13.763	
  83:     0xaaaae82f3be0 - tokio::runtime::blocking::pool::Task::run::h7280e16f7b817952
2024-08-29 23:18:13.762	
                               at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.0/src/runtime/task/mod.rs:464:9
2024-08-29 23:18:13.761	
  82:     0xaaaae82f3be0 - tokio::runtime::task::UnownedTask<S>::run::hbbe531544349f33c
2024-08-29 23:18:13.759	
                               at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.0/src/runtime/task/raw.rs:201:18
2024-08-29 23:18:13.758	
  81:     0xaaaae82f3be0 - tokio::runtime::task::raw::RawTask::poll::hf805025bc0bae7ea
2024-08-29 23:18:13.757	
                               at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.0/src/runtime/task/harness.rs:153:15
2024-08-29 23:18:13.755	
  80:     0xaaaae8314868 - tokio::runtime::task::harness::Harness<T,S>::poll::hadb06382fb57491f
2024-08-29 23:18:13.754	
                               at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.0/src/runtime/task/harness.rs:208:27
2024-08-29 23:18:13.753	
  79:     0xaaaae8314868 - tokio::runtime::task::harness::Harness<T,S>::poll_inner::hde5a267f5ec38980
2024-08-29 23:18:13.752	
                               at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.0/src/runtime/task/harness.rs:473:18
2024-08-29 23:18:13.750	
  78:     0xaaaae8314868 - tokio::runtime::task::harness::poll_future::h82a36abd5ceef0c8
2024-08-29 23:18:13.750	
                               at /rustc/72fdf913c53dd0e75313ba83e4aa80df3f6e2871/library/std/src/panic.rs:149:14
2024-08-29 23:18:13.749	
  77:     0xaaaae8314868 - std::panic::catch_unwind::h44a80628121759e8
2024-08-29 23:18:13.749	
                               at /rustc/72fdf913c53dd0e75313ba83e4aa80df3f6e2871/library/std/src/panicking.rs:523:19
2024-08-29 23:18:13.749	
  76:     0xaaaae8314868 - std::panicking::try::h5bfacef9e8d015c5
2024-08-29 23:18:13.749	
                               at /rustc/72fdf913c53dd0e75313ba83e4aa80df3f6e2871/library/std/src/panicking.rs:559:40
2024-08-29 23:18:13.749	
  75:     0xaaaae8314868 - std::panicking::try::do_call::h4dd6abf00af54fcc
2024-08-29 23:18:13.749	
                               at /rustc/72fdf913c53dd0e75313ba83e4aa80df3f6e2871/library/core/src/panic/unwind_safe.rs:272:9
2024-08-29 23:18:13.749	
  74:     0xaaaae8314868 - <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::hb2bc03d11d7f0819
2024-08-29 23:18:13.749	
                               at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.0/src/runtime/task/harness.rs:485:19
2024-08-29 23:18:13.749	
  73:     0xaaaae8314868 - tokio::runtime::task::harness::poll_future::{{closure}}::ha31dc7a365256760
2024-08-29 23:18:13.749	
                               at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.0/src/runtime/task/core.rs:317:30
2024-08-29 23:18:13.749	
  72:     0xaaaae832f8ec - tokio::runtime::task::core::Core<T,S>::poll::h5791eb96afb53332
2024-08-29 23:18:13.749	
                               at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.0/src/loom/std/unsafe_cell.rs:16:9
2024-08-29 23:18:13.749	
  71:     0xaaaae832f8ec - tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut::h402f7a5d6d135d81
2024-08-29 23:18:13.749	
                               at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.0/src/runtime/task/core.rs:328:17
2024-08-29 23:18:13.749	
  70:     0xaaaae832f8ec - tokio::runtime::task::core::Core<T,S>::poll::{{closure}}::h5fe0e288657cc3a5
2024-08-29 23:18:13.749	
                               at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.40/src/instrument.rs:321:9
2024-08-29 23:18:13.749	
  69:     0xaaaae83284dc - <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll::h8bb151d0a954295b
2024-08-29 23:18:13.749	
                               at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.0/src/runtime/blocking/task.rs:42:21
2024-08-29 23:18:13.749	
  68:     0xaaaae8318ff0 - <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll::h5968fe8c9bb86772
2024-08-29 23:18:13.749	
                               at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.0/src/runtime/scheduler/multi_thread/worker.rs:455:45
2024-08-29 23:18:13.749	
  67:     0xaaaae8318ff0 - tokio::runtime::scheduler::multi_thread::worker::Launch::launch::{{closure}}::hd2385adf11fd71c4
2024-08-29 23:18:13.749	
                               at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.0/src/runtime/scheduler/multi_thread/worker.rs:487:5
2024-08-29 23:18:13.748	
  66:     0xaaaae82fb9e4 - tokio::runtime::scheduler::multi_thread::worker::run::h403563c0d8fb93bb
2024-08-29 23:18:13.748	
                               at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.0/src/runtime/context/runtime.rs:65:16
2024-08-29 23:18:13.748	
  65:     0xaaaae8311044 - tokio::runtime::context::runtime::enter_runtime::hc009ada14663437e
2024-08-29 23:18:13.748	
                               at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.0/src/runtime/scheduler/multi_thread/worker.rs:495:9
2024-08-29 23:18:13.748	
  64:     0xaaaae8311044 - tokio::runtime::scheduler::multi_thread::worker::run::{{closure}}::h115a64a4fb372cc1
2024-08-29 23:18:13.748	
                               at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.0/src/runtime/context.rs:180:17
2024-08-29 23:18:13.748	
  63:     0xaaaae8311044 - tokio::runtime::context::set_scheduler::hfe1bae3a499d675b
2024-08-29 23:18:13.748	
                               at /rustc/72fdf913c53dd0e75313ba83e4aa80df3f6e2871/library/std/src/thread/local.rs:260:9
2024-08-29 23:18:13.748	
  62:     0xaaaae8311044 - std::thread::local::LocalKey<T>::with::hd87e041d4f126461
2024-08-29 23:18:13.748	
                               at /rustc/72fdf913c53dd0e75313ba83e4aa80df3f6e2871/library/std/src/thread/local.rs:283:12
2024-08-29 23:18:13.748	
  61:     0xaaaae8311044 - std::thread::local::LocalKey<T>::try_with::h417812abe93de898
2024-08-29 23:18:13.748	
                               at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.0/src/runtime/context.rs:180:26
2024-08-29 23:18:13.748	
  60:     0xaaaae8311044 - tokio::runtime::context::set_scheduler::{{closure}}::h660e2e61585fa491
2024-08-29 23:18:13.748	
                               at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.0/src/runtime/context/scoped.rs:40:9
2024-08-29 23:18:13.748	
  59:     0xaaaae82f751c - tokio::runtime::context::scoped::Scoped<T>::set::h06456b1a29b52c32
2024-08-29 23:18:13.748	
                               at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.0/src/runtime/scheduler/multi_thread/worker.rs:500:21
2024-08-29 23:18:13.748	
  58:     0xaaaae82f751c - tokio::runtime::scheduler::multi_thread::worker::run::{{closure}}::{{closure}}::h087df549dadc8e2b
2024-08-29 23:18:13.748	
                               at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.0/src/runtime/scheduler/multi_thread/worker.rs:535:24
2024-08-29 23:18:13.748	
  57:     0xaaaae82f751c - tokio::runtime::scheduler::multi_thread::worker::Context::run::h9e74e2a138c8c82a
2024-08-29 23:18:13.747	
                               at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.0/src/runtime/scheduler/multi_thread/worker.rs:584:9
2024-08-29 23:18:13.747	
  56:     0xaaaae82fbc40 - tokio::runtime::scheduler::multi_thread::worker::Context::run_task::h1d75b7d799b485c1
2024-08-29 23:18:13.747	
                               at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.0/src/runtime/coop.rs:73:5
2024-08-29 23:18:13.747	
  55:     0xaaaae82fbc40 - tokio::runtime::coop::budget::h8c574184279a4fc8
2024-08-29 23:18:13.747	
                               at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.0/src/runtime/coop.rs:107:5
2024-08-29 23:18:13.747	
  54:     0xaaaae82fbc40 - tokio::runtime::coop::with_budget::hdf0a9d79c8ccca10
2024-08-29 23:18:13.747	
                               at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.0/src/runtime/scheduler/multi_thread/worker.rs:585:18
2024-08-29 23:18:13.747	
  53:     0xaaaae82fbc40 - tokio::runtime::scheduler::multi_thread::worker::Context::run_task::{{closure}}::hf6e1428375dd515f
2024-08-29 23:18:13.747	
                               at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.0/src/runtime/task/mod.rs:427:9
2024-08-29 23:18:13.747	
  52:     0xaaaae82fbc40 - tokio::runtime::task::LocalNotified<S>::run::hc13aa9870db61a6d
2024-08-29 23:18:13.747	
                               at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.0/src/runtime/task/raw.rs:201:18
2024-08-29 23:18:13.747	
  51:     0xaaaae82fbc40 - tokio::runtime::task::raw::RawTask::poll::hf805025bc0bae7ea
2024-08-29 23:18:13.747	
                               at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.0/src/runtime/task/harness.rs:153:15
2024-08-29 23:18:13.747	
  50:     0xaaaae0d23198 - tokio::runtime::task::harness::Harness<T,S>::poll::he1a8bda4c4177b78
2024-08-29 23:18:13.747	
                               at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.0/src/runtime/task/harness.rs:208:27
2024-08-29 23:18:13.747	
  49:     0xaaaae0d23198 - tokio::runtime::task::harness::Harness<T,S>::poll_inner::h8b03736be440977e
2024-08-29 23:18:13.747	
                               at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.0/src/runtime/task/harness.rs:473:18
2024-08-29 23:18:13.747	
  48:     0xaaaae0d23198 - tokio::runtime::task::harness::poll_future::h96a1fc0e7cf0b9ba
2024-08-29 23:18:13.747	
                               at /rustc/72fdf913c53dd0e75313ba83e4aa80df3f6e2871/library/std/src/panic.rs:149:14
2024-08-29 23:18:13.747	
  47:     0xaaaae0d23198 - std::panic::catch_unwind::had0ef6d68301c59a
2024-08-29 23:18:13.747	
                               at /rustc/72fdf913c53dd0e75313ba83e4aa80df3f6e2871/library/std/src/panicking.rs:523:19
2024-08-29 23:18:13.747	
  46:     0xaaaae0d23198 - std::panicking::try::h52a837f11f27a6b9
2024-08-29 23:18:13.747	
                               at /rustc/72fdf913c53dd0e75313ba83e4aa80df3f6e2871/library/std/src/panicking.rs:559:40
2024-08-29 23:18:13.747	
  45:     0xaaaae0d23198 - std::panicking::try::do_call::h01036c5729d3fe0b
2024-08-29 23:18:13.747	
                               at /rustc/72fdf913c53dd0e75313ba83e4aa80df3f6e2871/library/core/src/panic/unwind_safe.rs:272:9
2024-08-29 23:18:13.747	
  44:     0xaaaae0d23198 - <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h3e14d0e0a7108719
2024-08-29 23:18:13.747	
                               at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.0/src/runtime/task/harness.rs:485:19
2024-08-29 23:18:13.747	
  43:     0xaaaae0d23198 - tokio::runtime::task::harness::poll_future::{{closure}}::hc2214e6b5fad52bb
2024-08-29 23:18:13.746	
                               at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.0/src/runtime/task/core.rs:317:30
2024-08-29 23:18:13.746	
  42:     0xaaaae0d02170 - tokio::runtime::task::core::Core<T,S>::poll::h3bb411d8c31b31d8
2024-08-29 23:18:13.746	
                               at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.0/src/loom/std/unsafe_cell.rs:16:9
2024-08-29 23:18:13.746	
  41:     0xaaaae0d02170 - tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut::hb05989d9ef0ef81c
2024-08-29 23:18:13.746	
                               at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.0/src/runtime/task/core.rs:328:17
2024-08-29 23:18:13.746	
  40:     0xaaaae0d02170 - tokio::runtime::task::core::Core<T,S>::poll::{{closure}}::h3041eb41527b59b4
2024-08-29 23:18:13.730	
                               at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.40/src/instrument.rs:321:9
2024-08-29 23:18:13.729	
  39:     0xaaaae0c67434 - <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll::hd2974a794a28bbde
2024-08-29 23:18:13.729	
                               at /root/.cargo/git/checkouts/foyer-9fcbb3f3d4fa5436-shallow/eaf4d43/foyer-storage/src/large/reclaimer.rs:82:63
2024-08-29 23:18:13.729	
  38:     0xaaaae0c67434 - foyer_storage::large::reclaimer::Reclaimer::open::{{closure}}::{{closure}}::h487b008dedbe653d
2024-08-29 23:18:13.729	
                               at /root/.cargo/git/checkouts/foyer-9fcbb3f3d4fa5436-shallow/eaf4d43/foyer-storage/src/large/reclaimer.rs:153:59
2024-08-29 23:18:13.729	
  37:     0xaaaae0c67434 - foyer_storage::large::reclaimer::ReclaimRunner<K,V,S>::run::{{closure}}::h8a013aaec186c47e
2024-08-29 23:18:13.728	
                               at /root/.cargo/git/checkouts/foyer-9fcbb3f3d4fa5436-shallow/eaf4d43/foyer-storage/src/large/reclaimer.rs:188:56
2024-08-29 23:18:13.728	
  36:     0xaaaae0c67434 - foyer_storage::large::reclaimer::ReclaimRunner<K,V,S>::handle::{{closure}}::h442760db88a96078
2024-08-29 23:18:13.727	
                               at /root/.cargo/git/checkouts/foyer-9fcbb3f3d4fa5436-shallow/eaf4d43/foyer-storage/src/large/scanner.rs:168:48
2024-08-29 23:18:13.727	
  35:     0xaaaae0c67434 - foyer_storage::large::scanner::RegionScanner::next_key::{{closure}}::h8e7320f1d56c4c86
2024-08-29 23:18:13.726	
                               at /root/.cargo/git/checkouts/foyer-9fcbb3f3d4fa5436-shallow/eaf4d43/foyer-storage/src/large/scanner.rs:74:62
2024-08-29 23:18:13.725	
  34:     0xaaaae0c1bab8 - foyer_storage::large::scanner::CachedDeviceReader::read::{{closure}}::hd339d8e884e676ad
2024-08-29 23:18:13.724	
                               at /root/.cargo/git/checkouts/foyer-9fcbb3f3d4fa5436-shallow/eaf4d43/foyer-storage/src/region.rs:92:48
2024-08-29 23:18:13.723	
  33:     0xaaaae0c1df00 - foyer_storage::region::Region::read::{{closure}}::hdf9f79fe9aadfb9e
2024-08-29 23:18:13.723	
                               at /root/.cargo/git/checkouts/foyer-9fcbb3f3d4fa5436-shallow/eaf4d43/foyer-storage/src/device/monitor.rs:171:40
2024-08-29 23:18:13.722	
  32:     0xaaaae0c1df00 - <foyer_storage::device::monitor::Monitored<D> as foyer_storage::device::Dev>::read::{{closure}}::hba65a6b53decaba9
2024-08-29 23:18:13.722	
                               at /root/.cargo/git/checkouts/foyer-9fcbb3f3d4fa5436-shallow/eaf4d43/foyer-storage/src/device/monitor.rs:117:91
2024-08-29 23:18:13.721	
  31:     0xaaaae0c1df00 - foyer_storage::device::monitor::Monitored<D>::read::{{closure}}::h5d413494dbdc0b92
2024-08-29 23:18:13.708	
                               at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/fastrace-0.7.2/src/future.rs:124:19
2024-08-29 23:18:13.708	
  30:     0xaaaae1014f88 - <fastrace::future::InSpan<T> as core::future::future::Future>::poll::h0cab54e90adb1954
2024-08-29 23:18:13.707	
                               at /root/.cargo/git/checkouts/foyer-9fcbb3f3d4fa5436-shallow/eaf4d43/foyer-storage/src/device/monitor.rs:124:57
2024-08-29 23:18:13.707	
  29:     0xaaaae1014f88 - foyer_storage::device::monitor::Monitored<D>::read::{{closure}}::{{closure}}::h0285e89b505476b3
2024-08-29 23:18:13.706	
                               at /root/.cargo/git/checkouts/foyer-9fcbb3f3d4fa5436-shallow/eaf4d43/foyer-storage/src/device/mod.rs:154:68
2024-08-29 23:18:13.706	
  28:     0xaaaae1014f88 - <foyer_storage::device::Device as foyer_storage::device::Dev>::read::{{closure}}::h41a45761992b1f32
2024-08-29 23:18:13.705	
                               at /root/.cargo/git/checkouts/foyer-9fcbb3f3d4fa5436-shallow/eaf4d43/foyer-storage/src/device/direct_fs.rs:183:91
2024-08-29 23:18:13.705	
  27:     0xaaaae1014f88 - <foyer_storage::device::direct_fs::DirectFsDevice as foyer_storage::device::Dev>::read::{{closure}}::haf2c8b492d4f7cd7
2024-08-29 23:18:13.704	
                               at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/fastrace-0.7.2/src/future.rs:124:19
2024-08-29 23:18:13.704	
  26:     0xaaaae1014f88 - <fastrace::future::InSpan<T> as core::future::future::Future>::poll::hc049be5e94eafbb1
2024-08-29 23:18:13.703	
                               at /root/.cargo/git/checkouts/foyer-9fcbb3f3d4fa5436-shallow/eaf4d43/foyer-storage/src/device/direct_fs.rs:195:23
2024-08-29 23:18:13.703	
  25:     0xaaaae1014f88 - <foyer_storage::device::direct_fs::DirectFsDevice as foyer_storage::device::Dev>::read::{{closure}}::{{closure}}::hced789b3603da7fa
2024-08-29 23:18:13.702	
                               at /root/.cargo/git/checkouts/foyer-9fcbb3f3d4fa5436-shallow/eaf4d43/foyer-storage/src/device/bytes.rs:261:20
2024-08-29 23:18:13.702	
  24:     0xaaaae1014f88 - foyer_storage::device::bytes::IoBytesMut::with_capacity::hc315db5157e548b7
2024-08-29 23:18:13.701	
                               at /rustc/72fdf913c53dd0e75313ba83e4aa80df3f6e2871/library/alloc/src/vec/mod.rs:699:20
2024-08-29 23:18:13.701	
  23:     0xaaaae1014f88 - alloc::vec::Vec<T,A>::with_capacity_in::h4790845c0490acb6
2024-08-29 23:18:13.700	
                               at /rustc/72fdf913c53dd0e75313ba83e4aa80df3f6e2871/library/alloc/src/raw_vec.rs:160:25
2024-08-29 23:18:13.700	
  22:     0xaaaae1014f88 - alloc::raw_vec::RawVec<T,A>::with_capacity_in::hbbb8dd111a07f408
2024-08-29 23:18:13.688	
                               at /rustc/72fdf913c53dd0e75313ba83e4aa80df3f6e2871/library/alloc/src/raw_vec.rs:593:29
2024-08-29 23:18:13.688	
  21:     0xaaaadc53703c - alloc::raw_vec::handle_error::he7e6964f1f31f7af
2024-08-29 23:18:13.688	
                               at /rustc/72fdf913c53dd0e75313ba83e4aa80df3f6e2871/library/alloc/src/raw_vec.rs:25:5
2024-08-29 23:18:13.687	
  20:     0xaaaadc536e48 - alloc::raw_vec::capacity_overflow::h9c0886e7c533a1ff
2024-08-29 23:18:13.687	
                               at /rustc/72fdf913c53dd0e75313ba83e4aa80df3f6e2871/library/core/src/panicking.rs:72:14
2024-08-29 23:18:13.686	
  19:     0xaaaadd9d6e34 - core::panicking::panic_fmt::hf916447f409c2977
2024-08-29 23:18:13.686	
                               at /rustc/72fdf913c53dd0e75313ba83e4aa80df3f6e2871/library/std/src/panicking.rs:652:5
2024-08-29 23:18:13.685	
  18:     0xaaaae826a6c8 - rust_begin_unwind
2024-08-29 23:18:13.685	
                               at /rustc/72fdf913c53dd0e75313ba83e4aa80df3f6e2871/library/std/src/sys_common/backtrace.rs:171:18
2024-08-29 23:18:13.685	
  17:     0xaaaae8269890 - std::sys_common::backtrace::__rust_end_short_backtrace::hb1a588d5cae29824
2024-08-29 23:18:13.684	
                               at /rustc/72fdf913c53dd0e75313ba83e4aa80df3f6e2871/library/std/src/panicking.rs:656:13
2024-08-29 23:18:13.684	
  16:     0xaaaae826a920 - std::panicking::begin_panic_handler::{{closure}}::h130bba524bd3d26b
2024-08-29 23:18:13.683	
                               at /rustc/72fdf913c53dd0e75313ba83e4aa80df3f6e2871/library/std/src/panicking.rs:799:13
2024-08-29 23:18:13.682	
  15:     0xaaaae826ab64 - std::panicking::rust_panic_with_hook::h8b6dcdad5fa83c38
2024-08-29 23:18:13.682	
                               at /rustc/72fdf913c53dd0e75313ba83e4aa80df3f6e2871/library/alloc/src/boxed.rs:2077:9
2024-08-29 23:18:13.681	
  14:     0xaaaae826ab64 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h4fb87aedeaa87f30
2024-08-29 23:18:13.680	
                               at /rustc/72fdf913c53dd0e75313ba83e4aa80df3f6e2871/library/std/src/panicking.rs:233:47
2024-08-29 23:18:13.680	
  13:     0xaaaae5ef9048 - std::panicking::update_hook::{{closure}}::hd76262f4fe241678
2024-08-29 23:18:13.679	
                               at /risingwave/src/utils/runtime/src/panic_hook.rs:25:9
2024-08-29 23:18:13.679	
  12:     0xaaaae5ef9048 - risingwave_rt::panic_hook::set_panic_hook::{{closure}}::ha08688f7da0b5c68
2024-08-29 23:18:13.678	
                               at /rustc/72fdf913c53dd0e75313ba83e4aa80df3f6e2871/library/alloc/src/boxed.rs:2077:9
2024-08-29 23:18:13.677	
  11:     0xaaaae5ef9048 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h27ddc9a91bfb6454
2024-08-29 23:18:13.673	
                               at /rustc/72fdf913c53dd0e75313ba83e4aa80df3f6e2871/library/std/src/panicking.rs:298:9
2024-08-29 23:18:13.673	
  10:     0xaaaae826a254 - std::panicking::default_hook::habb52c27eba39fa1
2024-08-29 23:18:13.672	
   9:     0xaaaae826a5ac - std::panicking::default_hook::{{closure}}::h673ec0d25d5839ed
2024-08-29 23:18:13.672	
                               at /rustc/72fdf913c53dd0e75313ba83e4aa80df3f6e2871/library/std/src/sys_common/backtrace.rs:34:9
2024-08-29 23:18:13.671	
   8:     0xaaaae82691f8 - std::sys_common::backtrace::print::h6a76a3e289b41b76
2024-08-29 23:18:13.670	
                               at /rustc/72fdf913c53dd0e75313ba83e4aa80df3f6e2871/library/std/src/sys_common/backtrace.rs:47:5
2024-08-29 23:18:13.667	
   7:     0xaaaae82691f8 - std::sys_common::backtrace::_print::ha084ca3dc112f7ce
2024-08-29 23:18:13.666	
                               at /rustc/72fdf913c53dd0e75313ba83e4aa80df3f6e2871/library/std/src/io/mod.rs:1835:15
2024-08-29 23:18:13.666	
   6:     0xaaaae826423c - std::io::Write::write_fmt::h92c5bdbd600095f4
2024-08-29 23:18:13.665	
                               at /rustc/72fdf913c53dd0e75313ba83e4aa80df3f6e2871/library/core/src/fmt/mod.rs:1168:21
2024-08-29 23:18:13.665	
   5:     0xaaaadd9da2a0 - core::fmt::write::h2ab4a0f6cb1c47e2
2024-08-29 23:18:13.664	
                               at /rustc/72fdf913c53dd0e75313ba83e4aa80df3f6e2871/library/core/src/fmt/rt.rs:165:63
2024-08-29 23:18:13.663	
   4:     0xaaaadd9da2a0 - core::fmt::rt::Argument::fmt::h97fcedd5c989dd8e
2024-08-29 23:18:13.661	
                               at /rustc/72fdf913c53dd0e75313ba83e4aa80df3f6e2871/library/std/src/sys_common/backtrace.rs:44:22
2024-08-29 23:18:13.661	
   3:     0xaaaae82693b0 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h59fe19f00e808c0f
2024-08-29 23:18:13.660	
                               at /rustc/72fdf913c53dd0e75313ba83e4aa80df3f6e2871/library/std/src/sys_common/backtrace.rs:68:5
2024-08-29 23:18:13.659	
   2:     0xaaaae82693b0 - std::sys_common::backtrace::_print_fmt::h8edb2ed98e6d043e
2024-08-29 23:18:13.659	
                               at /rustc/72fdf913c53dd0e75313ba83e4aa80df3f6e2871/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
2024-08-29 23:18:13.658	
   1:     0xaaaae82693b0 - std::backtrace_rs::backtrace::trace_unsynchronized::h09825ba824b25c03
2024-08-29 23:18:13.658	
                               at /rustc/72fdf913c53dd0e75313ba83e4aa80df3f6e2871/library/std/src/../../backtrace/src/backtrace/libunwind.rs:116:5
2024-08-29 23:18:13.657	
   0:     0xaaaae82693b0 - std::backtrace_rs::backtrace::libunwind::trace::h22abe6941b6c364e
2024-08-29 23:18:13.657	
stack backtrace:
2024-08-29 23:18:13.657	
capacity overflow
2024-08-29 23:18:13.657	
thread 'foyer.data-unified' panicked at library/alloc/src/raw_vec.rs:25:5:


```

**Comment by MrCroxx** [comment]
May related to #676 #677 .

**Comment by MrCroxx** [comment]
Looks good with #677 . Close. Feel free to reopen this issue if the error appears again.
