### ISSUE TITLE
edge case: panic at write assert with DirectFsDeviceOptionsBuilder capacity=4096

### ISSUE THREAD

**Issue by kemingy** [foyer-rs/foyer#710]
Error messages:

```text
thread 'tokio-runtime-worker' panicked at foyer/foyer-storage/src/device/direct_fs.rs:159:9:
offset (0) + aligned (8192) = total (8192) <= region size (4096)
```

Code to reproduce:

```rust
use foyer::{DirectFsDeviceOptionsBuilder, HybridCache, HybridCacheBuilder};

#[tokio::main]
async fn main() -> anyhow::Result<()> {
    let dir = tempfile::tempdir()?;

    let hybrid: HybridCache<u32, Vec<f32>> = HybridCacheBuilder::new()
        .memory(1024)
        .storage()
        .with_device_config(
            DirectFsDeviceOptionsBuilder::new(dir.path())
                .with_capacity(4 * 1024)
                .build(),
        )
        .build()
        .await?;

    for i in 0..1024 {
        hybrid.insert(i, vec![i as f32; 1024]);
    }

    for i in 0..1024 {
        if !hybrid.contains(&i) {
            println!("Key {} is missing", i);
        } else {
            let entry = hybrid.get(&i).await?;
            assert_eq!(entry.expect(&format!("{} value is missing", i)).value().len(), 1024);
        }
    }
    println!("finished");

    Ok(())
}

**Comment by kemingy** [comment]
BTW, if the DirectFsDeviceOptionsBuilder capacity is less than 4096, it will panic due to the `align_v` function.

```text
thread 'main' panicked at foyer-storage/src/device/direct_fs.rs:301:60:
attempt to calculate the remainder with a divisor of zero
```

**Comment by MrCroxx** [comment]
Hi @kemingy . Thanks for reporting. It is by design because foyer assumes that the block device can be 4K aligned.

May I ask why you need a disk cache that small?

**Comment by MrCroxx** [comment]
The region is the grain for disk cache eviction. It is supposed to be several MBs for most cases.

**Comment by kemingy** [comment]
> Hi @kemingy . Thanks for reporting. It is by design because foyer assumes that the block device can be 4K aligned.
> 
> May I ask why you need a disk cache that small?

It's just an edge case. I run into this error during some small random tests. This doesn't affect my normal use case.

**Comment by MrCroxx** [comment]
Okay. Let me add some docs and warning for it.
